FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

ADD ./scripts /home/scripts
WORKDIR /home/scripts

RUN apt-get update && apt-get install -y
RUN apt-get install postgresql -y
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install wget -y
RUN apt-get install unzip -y
RUN mkdir -p ./tools/osmosis
RUN wget -P ./tools/osmosis https://github.com/openstreetmap/osmosis/releases/download/0.48.3/osmosis-0.48.3.tgz 
RUN tar xvfz ./tools/osmosis/osmosis-0.48.3.tgz -C ./tools/osmosis
RUN rm ./tools/osmosis/osmosis-0.48.3.tgz
RUN chmod a+x ./tools/osmosis/bin/osmosis
RUN unzip ./sparqlify.zip -d ./tools/

