FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y
RUN apt-get install postgresql -y
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install wget -y
RUN apt-get install unzip -y
RUN apt-get install python3-pip -y
RUN pip install geopy -y

