FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y
RUN apt-get install postgresql -y
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install wget -y
RUN apt-get install unzip -y
RUN apt-get install curl -y
RUN apt-get install jq -y
RUN apt-get install virtuoso-opensource-7-bin -y

