FROM ubuntu:22.04
RUN apt-get update && apt-get install -y
RUN apt-get install osmosis -y
#RUN osmosis --read-apidb database="map" user="admin" password="admin" --write-xml file="./../map/florence-partial.osm"
