FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y
RUN apt-get install osmosis -y
RUN apt-get install postgresql -y
RUN apt-get install git -y
RUN apt-get install maven -y

